title: AWPL Docs
description: User Documentation for AWPL (Abstract Workflow Pipeline Language)
theme: just-the-docs

url: "https://spice-uibk.github.io"
baseurl: "/awpl-docs"

aux_links:
  Template Repository: https://github.com/Spice-uibk/awpl-docs

callouts:
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow
